### ISSUE TITLE
Skein application keeps running forever

### ISSUE THREAD

**Issue by fhoering** [jcrist/skein#172] opened 2019-05-01 13:37 UTC
In tf-yarn we have sometimes issues with our application never shutting down and keep running forever.

One example is that one worker fails before having sent the init message to the kv store and as tensorflow needs all workers to be ready before being able to start we keep waiting forever for the startup message.

I had a look at the shutdown logic in [ApplicationMaster.java](https://github.com/jcrist/skein/blob/master/java/src/main/java/com/anaconda/skein/ApplicationMaster.java)
Currently we shut down the application if there is no retry configured (or number of retries exceeded), one container fails and we have no active containers anymore (no waiting, requested & running).
In our use case, distributed tensorflow, I think it would make more sense to shutdown as soon as one node fails (in reality is is more complicated then that, I think I can be robust to worker failures but not chief and ps failures)

I'm also wondering what happens if we ask for a lot of containers and Yarn never assigns us the requested ones. I'm not sure if there is any guarantee on getting the number of containers we asked for. In this case it means that a lot of containers will stay in requested mode and the app will never shut down either.
Quickly trying with 1000 containers it takes a lot time at least. So even if one container fails quite soon the app will keep running until all containers got assigned from yarn.

Do you think we can we somehow change this logic to fail fast, for example fail as soon as one container fails or maybe even as soon as one type of container fails ?

**Comment by jcrist** [comment] 2019-05-01 15:13
> Currently we shut down the application if there is no retry configured (or number of retries exceeded), one container fails and we have no active containers anymore (no waiting, requested & running).

This isn't exactly correct (or maybe it is and I'm misunderstanding you). An application will shutdown if any of the following are true:
- A user defined script running on the application master exits
- A container exits with a non-zero exit code, and its corresponding service is out of retries
- All containers have finished and no script is running on the application master

> In our use case, distributed tensorflow, I think it would make more sense to shutdown as soon as one node fails

This should be happening with the existing code today provided you're not enabling restarts. Does the process definitely exit with a non-zero exit code?

> I'm also wondering what happens if we ask for a lot of containers and Yarn never assigns us the requested ones.

Currently we don't have a strong answer for this. Most applications I've written using Skein have a process monitoring the application state, enabling timeouts. Since there are many different behaviors people would want I can't think of a good way to bake this into Skein's configuration.

One way to handle this yourself would be to have a monitor process. When a worker starts, it registers itself with the key value store - the monitor process can then watch for these events, and if a requested worker fails to register in time it can act appropriately. I'd probably have this process run as part of the application master: https://jcrist.github.io/skein/specification.html#specification-master.

**Comment by fhoering** [comment] 2019-05-01 19:08
Thanks for the tip with the monitor process. I will have a look into that.

> This should be happening with the existing code today provided you're not enabling restarts. Does the process definitely exit with a non-zero exit code?

I didn't check but what I observe is that the skein UI displays the container as red/failed. So I conclude it is seen by skein/yarn as failed and exited with non zero exit code.

> A container exits with a non-zero exit code, and its corresponding service is out of retries

I use 0 retries. If I understand the code correctly this is done here:
l1319 in ApplicationMaster.java:
```
if (isFinished()) {
            maybeShutdown();
}
```

Finally I think what I would like to have is just removing the if condition which if I understand correctly would mean shutdown the application if one container fails (even if there are still containers running or requested)

**Comment by jcrist** [comment] 2019-05-01 20:10
Ah, good catch! What I stated above was the intended behavior, but it wasn't implemented properly (surprised this wasn't caught until now). Somehow missed adding a test for it - this bug has existed for a long time :(.

This should be fixed by #173. Given everything's ok, I can push a bugfix release pretty quick. If you want, feel free to try that branch out to ensure it fixes your problem (it should).

**Closed** 2019-05-01 21:16 UTC

**Comment by fhoering** [comment] 2019-05-02 15:04
Thanks. I tried with master branch. It fixes the issue. 
Yes if you can release a new version it would be nice.

I also looked at the fix and I have the impression that there is a the double check that basically does the same thing.

`if (isFinished() || isFailed())` seems to be the same as what we do in `maybeShutdown` ( // Fail if any service is failed
// Succeed if no driver, all services are finished, and none failed)

**Comment by jcrist** [comment] 2019-05-02 15:07
Yeah, checking here is likely a premature optimization - the full `maybeShutdown` has to temporarily lock all the services, while this only locks them if there is a chance that shutdown would happen.

**Comment by fhoering** [comment] 2019-05-02 15:25
OK. Thanks

**Comment by jcrist** [comment] 2019-05-02 15:57
0.7.2 is available on PyPI, conda builds should be done in the next few hours.
